env:
  browser: true
  es2021: true
  mocha: true
extends:
  - plugin:react/recommended
  - standard
  - plugin:chai-friendly/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - chai-friendly
rules: {
  "no-unused-expressions": 0,
  "chai-friendly/no-unused-expressions": 2
}
settings: 
  import/resolver: node
  react: 
    version: "detect"
