module.exports = {
  parserPreset: {
    parserOpts: {
      headerPattern: /^(?<type>.*\s\w*)(?:\((?<scope>.*)\))?!?:\s(?<subject>(?:(?!#).)*(?:(?!\s).))$/
    },
    headerCorrespondence: ['type', 'ticket', 'subject']
  },
  rules: {
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
    'header-max-length': [2, 'always', 72],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'subject-empty': [2, 'never'],
    'subject-exclamation-mark': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'type-enum': [2, 'always', [
      ':tada: init',
      ':new:',
      ':new: feature',
      ':bookmark:',
      ':bookmark: release',
      ':bookmark: tag',
      ':bug:',
      ':bug: fix',
      ':ambulance:',
      ':ambulance: fix',
      ':globe_with_meridians:',
      ':globe_with_meridians: i18n',
      ':lipstick:',
      ':clapper:',
      ':rotating_light:',
      ':wrench:',
      ':wrench: conf',
      ':heavy_plus_sign:',
      ':heavy_plus_sign: deps',
      ':heavy_minus_sign:',
      ':heavy_minus_sign: deps',
      ':arrow_up:',
      ':arrow_up: deps',
      ':arrow_down:',
      ':arrow_down: deps',
      ':zap:',
      ':chart_with_upwards_trend:',
      ':rocket:',
      ':white_check_mark:',
      ':memo:',
      ':hammer:',
      ':art:',
      ':fire:',
      ':pencil2:',
      ':pencil2: typo',
      ':construction:',
      ':wastebasket:',
      ':wastebasket: drop',
      ':wheelchair:',
      ':construction_worker:',
      ':construction_worker: ci',
      ':green_heart:',
      ':green_heart: ci',
      ':lock:',
      ':whale:',
      ':apple:',
      ':apple: fix',
      ':penguin:',
      ':penguin: fix',
      ':checkered_flag:',
      ':checkered_flag: fix',
      ':twisted_rightwards_arrows:',
      ':twisted_rightwards_arrows: merge'
    ]]
  }
}
